service: Naan # NOTE: update this with your service name
provider:
  name: aws
  runtime: python3.6
package:
  include:
    - weather.py
  exclude:
    - weather_test.py

functions:
  getWeather:
    handler: handler
    events:
      - http:
          path: weather
          method: get